In [1]:
print("Hello VariantX")

Hello VariantX

In [2]:
import pandas as pd
import pronto

print("Everything works!")

Everything works!

In [3]:
ontology = pronto.Ontology("../data/raw/hpo/hp.obo")

print(len(list(ontology.terms())))

C:\Users\ferna\AppData\Local\Temp\ipykernel_24628\3326114599.py:1: UnicodeWarning: unsound encoding, assuming ISO-8859-1 (73% confidence)
  ontology = pronto.Ontology("../data/raw/hpo/hp.obo")

19944

In [4]:
rows = []

for term in ontology.terms():
    rows.append({
        "HPO_ID": term.id,
        "Name": term.name,
        "Definition": term.definition
    })

hpo_df = pd.DataFrame(rows)

In [5]:
hpo_df.head()

,HPO_ID,Name,Definition
0,HP:0000001,All,None
1,HP:0000002,Abnormality of body height,Deviation from the norm of height with respect...
2,HP:0000003,Multicystic kidney dysplasia,Multicystic dysplasia of the kidney is charact...
3,HP:0000005,Mode of inheritance,The pattern in which a particular genetic trai...
4,HP:0000006,Autosomal dominant inheritance,A mode of inheritance that is observed for tra...

In [6]:
hpo_df.to_csv(
    "../data/interim/hpo_tables/hpo_terms.csv",
    index=False
)

In [7]:
phenotype_df = pd.read_csv(
    "../data/raw/hpo/phenotype.hpoa",
    sep="\t",
    comment="#"
)

C:\Users\ferna\AppData\Local\Temp\ipykernel_24628\3703215296.py:1: DtypeWarning: Columns (2,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  phenotype_df = pd.read_csv(

In [8]:
phenotype_df.head()

,database_id,disease_name,qualifier,hpo_id,reference,evidence,onset,frequency,sex,modifier,aspect,biocuration
0,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0011097,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
1,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0002187,PMID:31675180,PCS,NaN,1/1,NaN,NaN,P,HPO:probinson[2021-06-21]
2,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0001518,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
3,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0032792,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]
4,OMIM:619340,Developmental and epileptic encephalopathy 96,NaN,HP:0011451,PMID:31675180,PCS,NaN,1/2,NaN,NaN,P,HPO:probinson[2021-06-21]

In [9]:
phenotype_df.to_csv(
    "../data/interim/hpo_tables/disease_hpo_annotations.csv",
    index=False
)

In [ ]:
clinvar_df.to_csv(
    "../data/interim/clinvar_tables/clinvar_variants.csv",
    index=False
)

In [ ]:
import pandas as pd
df = pd.read_csv("../data/interim/hpo_tables/disease_hpo_annotations.csv")
print(df["frequency"].value_counts(dropna=False).head(30))

frequency
NaN           64151
HP:0040283    45225
HP:0040282    40048
HP:0040281    25797
1/1           18123
2/2            7596
HP:0040284     6942
1/2            6193
3/3            4244
1/3            4142
1/4            3363
4/4            2929
1/5            2342
2/3            1990
5/5            1810
1/6            1777
2/4            1542
1/7            1469
6/6            1306
2/5            1223
3/4            1136
1/8            1014
7/7             970
1/9             960
2/6             859
1/10            805
3/5             775
1/12            714
8/8             695
2/7             668
Name: count, dtype: int64

C:\Users\ferna\AppData\Local\Temp\ipykernel_30288\3015024275.py:2: DtypeWarning: Columns (2,6,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/interim/hpo_tables/disease_hpo_annotations.csv")

: