In [1]:
import pandas as pd

In [2]:
clingen_df = pd.read_csv(
    "../data/raw/clingen/ClinGen-Dosage-Sensitivity-2026-06-11.csv"
)

In [3]:
clingen_df.head()

,CLINGEN DOSAGE SENSITIVITY CURATIONS,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,FILE CREATED: 2026-06-11,NaN,NaN,NaN,NaN,NaN
1,WEBPAGE: https://search.clinicalgenome.org/kb/...,NaN,NaN,NaN,NaN,NaN
2,+++++++++++,+++++++,++++++++++++++++++,+++++++++++++++++,+++++++++++++,++++
3,GENE SYMBOL,HGNC ID,HAPLOINSUFFICIENCY,TRIPLOSENSITIVITY,ONLINE REPORT,DATE
4,+++++++++++,+++++++,++++++++++++++++++,+++++++++++++++++,+++++++++++++,++++

In [4]:
clingen_df.columns

Index(['CLINGEN DOSAGE SENSITIVITY CURATIONS', 'Unnamed: 1', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5'],
      dtype='str')

In [5]:
clingen_df = pd.read_csv(
    "../data/raw/clingen/ClinGen-Dosage-Sensitivity-2026-06-11.csv",
    skiprows=4
)

In [6]:
clingen_df.head()

,GENE SYMBOL,HGNC ID,HAPLOINSUFFICIENCY,TRIPLOSENSITIVITY,ONLINE REPORT,DATE
0,+++++++++++,+++++++,++++++++++++++++++,+++++++++++++++++,+++++++++++++,++++
1,A4GALT,HGNC:18149,Gene Associated with Autosomal Recessive Pheno...,No Evidence for Triplosensitivity,https://search.clinicalgenome.org/kb/gene-dosa...,2014-12-11T15:51:23+00:00
2,AAGAB,HGNC:25662,Sufficient Evidence for Haploinsufficiency,No Evidence for Triplosensitivity,https://search.clinicalgenome.org/kb/gene-dosa...,2013-02-28T20:17:25+00:00
3,AARS1,HGNC:20,No Evidence for Haploinsufficiency,No Evidence for Triplosensitivity,https://search.clinicalgenome.org/kb/gene-dosa...,2018-01-11T20:05:45+00:00
4,AARS2,HGNC:21022,Gene Associated with Autosomal Recessive Pheno...,Not yet evaluated,https://search.clinicalgenome.org/kb/gene-dosa...,2025-06-27T09:19:05-04:00

In [7]:
clingen_df.columns

Index(['GENE SYMBOL', 'HGNC ID', 'HAPLOINSUFFICIENCY', 'TRIPLOSENSITIVITY',
       'ONLINE REPORT', 'DATE'],
      dtype='str')

In [8]:
gene_dosage_df = clingen_df[
    [
        "GENE SYMBOL",
        "HAPLOINSUFFICIENCY",
        "TRIPLOSENSITIVITY"
    ]
]

In [9]:
gene_dosage_df.columns = [
    "gene_symbol",
    "haploinsufficiency_score",
    "triplosensitivity_score"
]

In [10]:
gene_dosage_df.head()

,gene_symbol,haploinsufficiency_score,triplosensitivity_score
0,+++++++++++,++++++++++++++++++,+++++++++++++++++
1,A4GALT,Gene Associated with Autosomal Recessive Pheno...,No Evidence for Triplosensitivity
2,AAGAB,Sufficient Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
3,AARS1,No Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
4,AARS2,Gene Associated with Autosomal Recessive Pheno...,Not yet evaluated

In [11]:
gene_dosage_df.to_csv(
    "../data/interim/clingen_tables/gene_dosage_table.csv",
    index=False
)

In [12]:
gene_dosage_df.head()

,gene_symbol,haploinsufficiency_score,triplosensitivity_score
0,+++++++++++,++++++++++++++++++,+++++++++++++++++
1,A4GALT,Gene Associated with Autosomal Recessive Pheno...,No Evidence for Triplosensitivity
2,AAGAB,Sufficient Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
3,AARS1,No Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
4,AARS2,Gene Associated with Autosomal Recessive Pheno...,Not yet evaluated

In [13]:
gene_dosage_df = gene_dosage_df[
    gene_dosage_df["gene_symbol"] != "++++++++++"
]

In [14]:
gene_dosage_df.head()

,gene_symbol,haploinsufficiency_score,triplosensitivity_score
0,+++++++++++,++++++++++++++++++,+++++++++++++++++
1,A4GALT,Gene Associated with Autosomal Recessive Pheno...,No Evidence for Triplosensitivity
2,AAGAB,Sufficient Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
3,AARS1,No Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
4,AARS2,Gene Associated with Autosomal Recessive Pheno...,Not yet evaluated

In [15]:
gene_dosage_df.iloc[0]

gene_symbol                        +++++++++++
haploinsufficiency_score    ++++++++++++++++++
triplosensitivity_score      +++++++++++++++++
Name: 0, dtype: str

In [16]:
gene_dosage_df = gene_dosage_df.iloc[1:]

In [17]:
gene_dosage_df.head()

,gene_symbol,haploinsufficiency_score,triplosensitivity_score
1,A4GALT,Gene Associated with Autosomal Recessive Pheno...,No Evidence for Triplosensitivity
2,AAGAB,Sufficient Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
3,AARS1,No Evidence for Haploinsufficiency,No Evidence for Triplosensitivity
4,AARS2,Gene Associated with Autosomal Recessive Pheno...,Not yet evaluated
5,AASS,Gene Associated with Autosomal Recessive Pheno...,No Evidence for Triplosensitivity

In [18]:
haplo_map = {
    "Sufficient Evidence for Haploinsufficiency": 3,
    "Some Evidence for Haploinsufficiency": 2,
    "Little Evidence for Haploinsufficiency": 1,
    "No Evidence for Haploinsufficiency": 0,
    "Not yet evaluated": -1,
    "Gene Associated with Autosomal Recessive Phenotype": 0
}

triplo_map = {
    "Sufficient Evidence for Triplosensitivity": 3,
    "Some Evidence for Triplosensitivity": 2,
    "Little Evidence for Triplosensitivity": 1,
    "No Evidence for Triplosensitivity": 0,
    "Not yet evaluated": -1,
    "Gene Associated with Autosomal Recessive Phenotype": 0
}

In [19]:
gene_dosage_df["haploinsufficiency_score"] = (
    gene_dosage_df["haploinsufficiency_score"]
    .map(haplo_map)
)

gene_dosage_df["triplosensitivity_score"] = (
    gene_dosage_df["triplosensitivity_score"]
    .map(triplo_map)
)

In [20]:
gene_dosage_df.head()

  gene_symbol  haploinsufficiency_score  triplosensitivity_score
1      A4GALT                       0.0                      0.0
2       AAGAB                       3.0                      0.0
3       AARS1                       0.0                      0.0
4       AARS2                       0.0                     -1.0
5        AASS                       0.0                      0.0

In [21]:
gene_dosage_df.isnull().sum()

gene_symbol                  0
haploinsufficiency_score    48
triplosensitivity_score      4
dtype: int64

In [22]:
haplo_map = {
    "Sufficient Evidence for Haploinsufficiency": 3,
    "Some Evidence for Haploinsufficiency": 2,
    "Little Evidence for Haploinsufficiency": 1,
    "No Evidence for Haploinsufficiency": 0,
    "Not yet evaluated": -1,
    "Gene Associated with Autosomal Recessive Phenotype": 0,
    "Dosage Sensitivity Unlikely": 0
}

In [23]:
triplo_map = {
    "Sufficient Evidence for Triplosensitivity": 3,
    "Some Evidence for Triplosensitivity": 2,
    "Little Evidence for Triplosensitivity": 1,
    "No Evidence for Triplosensitivity": 0,
    "Not yet evaluated": -1,
    "Gene Associated with Autosomal Recessive Phenotype": 0,
    "Dosage Sensitivity Unlikely": 0
}

In [24]:
clingen_df["HAPLOINSUFFICIENCY"].value_counts()

HAPLOINSUFFICIENCY
Gene Associated with Autosomal Recessive Phenotype    757
Sufficient Evidence for Haploinsufficiency            423
No Evidence for Haploinsufficiency                    319
Little Evidence for Haploinsufficiency                143
Dosage Sensitivity Unlikely for Haploinsufficiency     34
Emerging Evidence for Haploinsufficiency               14
++++++++++++++++++                                      1
Name: count, dtype: int64

In [25]:
clingen_df["TRIPLOSENSITIVITY"].value_counts()

TRIPLOSENSITIVITY
No Evidence for Triplosensitivity                    1402
Not yet evaluated                                     270
Little Evidence for Triplosensitivity                  11
Dosage Sensitivity Unlikely for Triplosensitivity       3
Sufficient Evidence for Triplosensitivity               3
+++++++++++++++++                                       1
Emerging Evidence for Triplosensitivity                 1
Name: count, dtype: int64

In [26]:
haplo_map = {
    "Sufficient Evidence for Haploinsufficiency": 3,
    "Some Evidence for Haploinsufficiency": 2,
    "Emerging Evidence for Haploinsufficiency": 1,
    "Little Evidence for Haploinsufficiency": 1,
    "No Evidence for Haploinsufficiency": 0,
    "Dosage Sensitivity Unlikely for Haploinsufficiency": 0,
    "Not yet evaluated": -1,
    "Gene Associated with Autosomal Recessive Phenotype": 0
}

In [27]:
triplo_map = {
    "Sufficient Evidence for Triplosensitivity": 3,
    "Some Evidence for Triplosensitivity": 2,
    "Emerging Evidence for Triplosensitivity": 1,
    "Little Evidence for Triplosensitivity": 1,
    "No Evidence for Triplosensitivity": 0,
    "Dosage Sensitivity Unlikely for Triplosensitivity": 0,
    "Not yet evaluated": -1,
    "Gene Associated with Autosomal Recessive Phenotype": 0
}

In [28]:
gene_dosage_df["haploinsufficiency_score"] = (
    clingen_df.iloc[1:]["HAPLOINSUFFICIENCY"]
    .map(haplo_map)
    .values
)

gene_dosage_df["triplosensitivity_score"] = (
    clingen_df.iloc[1:]["TRIPLOSENSITIVITY"]
    .map(triplo_map)
    .values
)

In [29]:
gene_dosage_df.isnull().sum()

gene_symbol                 0
haploinsufficiency_score    0
triplosensitivity_score     0
dtype: int64

In [30]:
gene_dosage_df.to_csv(
    "../data/interim/clingen_tables/gene_dosage_table.csv",
    index=False
)