In [2]:
import gzip

In [3]:
with gzip.open(
    "../data/raw/gnomad_sv/gnomad.v4.1.sv.sites.vcf.gz",
    "rt"
) as f:

    for line in f:
        if line.startswith("#CHROM"):
            print(line)
            break

#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO

In [4]:
with gzip.open(
    "../data/raw/gnomad_sv/gnomad.v4.1.sv.sites.vcf.gz",
    "rt"
) as f:

    found_header = False

    for line in f:

        if line.startswith("#CHROM"):
            found_header = True
            continue

        if found_header:
            print(line)
            break

chr1	10000	gnomAD-SV_v3_DUP_chr1_01c2781c	N	<DUP>	134	HIGH_NCR	ALGORITHMS=depth;CHR2=chr1;END=295666;EVIDENCE=BAF,RD;LOW_CONFIDENCE_REPETITIVE_LARGE_DUP;NCR=0.466928;PCRMINUS_NCR=0.432727;PCRPLUS_NCR=0.855144;PREDICTED_COPY_GAIN=OR4F5;SVLEN=285666;SVTYPE=DUP;AN=69594;AC=139;AF=0.001997;N_BI_GENOS=34797;N_HOMREF=34658;N_HET=139;N_HOMALT=0;FREQ_HOMREF=0.996005;FREQ_HET=0.0039946;FREQ_HOMALT=0;AN_afr=22722;AC_afr=121;AF_afr=0.005325;N_BI_GENOS_afr=11361;N_HOMREF_afr=11240;N_HET_afr=121;N_HOMALT_afr=0;FREQ_HOMREF_afr=0.98935;FREQ_HET_afr=0.0106505;FREQ_HOMALT_afr=0;AN_ami=418;AC_ami=0;AF_ami=0;N_BI_GENOS_ami=209;N_HOMREF_ami=209;N_HET_ami=0;N_HOMALT_ami=0;FREQ_HOMREF_ami=1;FREQ_HET_ami=0;FREQ_HOMALT_ami=0;AN_amr=6818;AC_amr=2;AF_amr=0.000293;N_BI_GENOS_amr=3409;N_HOMREF_amr=3407;N_HET_amr=2;N_HOMALT_amr=0;FREQ_HOMREF_amr=0.999413;FREQ_HET_amr=0.000586682;FREQ_HOMALT_amr=0;AN_asj=1472;AC_asj=0;AF_asj=0;N_BI_GENOS_asj=736;N_HOMREF_asj=736;N_HET_asj=0;N_HOMALT_asj=0;FREQ_HOMREF_asj=1;FREQ_HET_asj=0;FREQ_HOMALT_asj=0;AN_eas=3400;AC_eas=1;AF_eas=0.000294;N_BI_GENOS_eas=1700;N_HOMREF_eas=1699;N_HET_eas=1;N_HOMALT_eas=0;FREQ_HOMREF_eas=0.999412;FREQ_HET_eas=0.000588235;FREQ_HOMALT_eas=0;AN_fin=2646;AC_fin=1;AF_fin=0.000378;N_BI_GENOS_fin=1323;N_HOMREF_fin=1322;N_HET_fin=1;N_HOMALT_fin=0;FREQ_HOMREF_fin=0.999244;FREQ_HET_fin=0.000755858;FREQ_HOMALT_fin=0;AN_mid=38;AC_mid=0;AF_mid=0;N_BI_GENOS_mid=19;N_HOMREF_mid=19;N_HET_mid=0;N_HOMALT_mid=0;FREQ_HOMREF_mid=1;FREQ_HET_mid=0;FREQ_HOMALT_mid=0;AN_nfe=28618;AC_nfe=10;AF_nfe=0.000349;N_BI_GENOS_nfe=14309;N_HOMREF_nfe=14299;N_HET_nfe=10;N_HOMALT_nfe=0;FREQ_HOMREF_nfe=0.999301;FREQ_HET_nfe=0.000698861;FREQ_HOMALT_nfe=0;AN_rmi=804;AC_rmi=2;AF_rmi=0.002488;N_BI_GENOS_rmi=402;N_HOMREF_rmi=400;N_HET_rmi=2;N_HOMALT_rmi=0;FREQ_HOMREF_rmi=0.995025;FREQ_HET_rmi=0.00497512;FREQ_HOMALT_rmi=0;AN_sas=2658;AC_sas=2;AF_sas=0.000752;N_BI_GENOS_sas=1329;N_HOMREF_sas=1327;N_HET_sas=2;N_HOMALT_sas=0;FREQ_HOMREF_sas=0.998495;FREQ_HET_sas=0.00150489;FREQ_HOMALT_sas=0;GRPMAX_AF=0.005325;AN_XY=33092;AC_XY=60;AF_XY=0.001813;N_BI_GENOS_XY=16546;N_HOMREF_XY=16486;N_HET_XY=60;N_HOMALT_XY=0;FREQ_HOMREF_XY=0.996374;FREQ_HET_XY=0.00362625;FREQ_HOMALT_XY=0;AN_XX=36502;AC_XX=79;AF_XX=0.002164;N_BI_GENOS_XX=18251;N_HOMREF_XX=18172;N_HET_XX=79;N_HOMALT_XX=0;FREQ_HOMREF_XX=0.995671;FREQ_HET_XX=0.00432853;FREQ_HOMALT_XX=0;AN_afr_XY=10902;AC_afr_XY=53;AF_afr_XY=0.004861;N_BI_GENOS_afr_XY=5451;N_HOMREF_afr_XY=5398;N_HET_afr_XY=53;N_HOMALT_afr_XY=0;FREQ_HOMREF_afr_XY=0.990277;FREQ_HET_afr_XY=0.00972299;FREQ_HOMALT_afr_XY=0;AN_afr_XX=11820;AC_afr_XX=68;AF_afr_XX=0.005753;N_BI_GENOS_afr_XX=5910;N_HOMREF_afr_XX=5842;N_HET_afr_XX=68;N_HOMALT_afr_XX=0;FREQ_HOMREF_afr_XX=0.988494;FREQ_HET_afr_XX=0.0115059;FREQ_HOMALT_afr_XX=0;AN_ami_XY=210;AC_ami_XY=0;AF_ami_XY=0;N_BI_GENOS_ami_XY=105;N_HOMREF_ami_XY=105;N_HET_ami_XY=0;N_HOMALT_ami_XY=0;FREQ_HOMREF_ami_XY=1;FREQ_HET_ami_XY=0;FREQ_HOMALT_ami_XY=0;AN_ami_XX=208;AC_ami_XX=0;AF_ami_XX=0;N_BI_GENOS_ami_XX=104;N_HOMREF_ami_XX=104;N_HET_ami_XX=0;N_HOMALT_ami_XX=0;FREQ_HOMREF_ami_XX=1;FREQ_HET_ami_XX=0;FREQ_HOMALT_ami_XX=0;AN_amr_XY=3744;AC_amr_XY=1;AF_amr_XY=0.000267;N_BI_GENOS_amr_XY=1872;N_HOMREF_amr_XY=1871;N_HET_amr_XY=1;N_HOMALT_amr_XY=0;FREQ_HOMREF_amr_XY=0.999466;FREQ_HET_amr_XY=0.000534188;FREQ_HOMALT_amr_XY=0;AN_amr_XX=3074;AC_amr_XX=1;AF_amr_XX=0.000325;N_BI_GENOS_amr_XX=1537;N_HOMREF_amr_XX=1536;N_HET_amr_XX=1;N_HOMALT_amr_XX=0;FREQ_HOMREF_amr_XX=0.999349;FREQ_HET_amr_XX=0.000650618;FREQ_HOMALT_amr_XX=0;AN_asj_XY=632;AC_asj_XY=0;AF_asj_XY=0;N_BI_GENOS_asj_XY=316;N_HOMREF_asj_XY=316;N_HET_asj_XY=0;N_HOMALT_asj_XY=0;FREQ_HOMREF_asj_XY=1;FREQ_HET_asj_XY=0;FREQ_HOMALT_asj_XY=0;AN_asj_XX=840;AC_asj_XX=0;AF_asj_XX=0;N_BI_GENOS_asj_XX=420;N_HOMREF_asj_XX=420;N_HET_asj_XX=0;N_HOMALT_asj_XX=0;FREQ_HOMREF_asj_XX=1;FREQ_HET_asj_XX=0;FREQ_HOMALT_asj_XX=0;AN_eas_XY=1768;AC_eas_XY=0;AF_eas_XY=0;N_BI_GENOS_eas_XY=884;N_HOMREF_eas_XY=884;N_HET_eas_XY=0;N_HOMALT_eas_XY=0;FREQ_HOMREF_eas_XY=1;FREQ_HET_eas_XY=0;FREQ_HOMALT_eas_XY=0;AN_eas_XX=1632;AC_eas_XX=1;AF_eas_XX=0.000613;N_BI_GENOS_eas_XX=816;N_HOMREF_eas_XX=815;N_HET_eas_XX=1;N_HOMALT_eas_XX=0;FREQ_HOMREF_eas_XX=0.998775;FREQ_HET_eas_XX=0.00122549;FREQ_HOMALT_eas_XX=0;AN_fin_XY=2020;AC_fin_XY=1;AF_fin_XY=0.000495;N_BI_GENOS_fin_XY=1010;N_HOMREF_fin_XY=1009;N_HET_fin_XY=1;N_HOMALT_fin_XY=0;FREQ_HOMREF_fin_XY=0.99901;FREQ_HET_fin_XY=0.000990099;FREQ_HOMALT_fin_XY=0;AN_fin_XX=626;AC_fin_XX=0;AF_fin_XX=0;N_BI_GENOS_fin_XX=313;N_HOMREF_fin_XX=313;N_HET_fin_XX=0;N_HOMALT_fin_XX=0;FREQ_HOMREF_fin_XX=1;FREQ_HET_fin_XX=0;FREQ_HOMALT_fin_XX=0;AN_mid_XY=18;AC_mid_XY=0;AF_mid_XY=0;N_BI_GENOS_mid_XY=9;N_HOMREF_mid_XY=9;N_HET_mid_XY=0;N_HOMALT_mid_XY=0;FREQ_HOMREF_mid_XY=1;FREQ_HET_mid_XY=0;FREQ_HOMALT_mid_XY=0;AN_mid_XX=20;AC_mid_XX=0;AF_mid_XX=0;N_BI_GENOS_mid_XX=10;N_HOMREF_mid_XX=10;N_HET_mid_XX=0;N_HOMALT_mid_XX=0;FREQ_HOMREF_mid_XX=1;FREQ_HET_mid_XX=0;FREQ_HOMALT_mid_XX=0;AN_nfe_XY=11426;AC_nfe_XY=2;AF_nfe_XY=0.000175;N_BI_GENOS_nfe_XY=5713;N_HOMREF_nfe_XY=5711;N_HET_nfe_XY=2;N_HOMALT_nfe_XY=0;FREQ_HOMREF_nfe_XY=0.99965;FREQ_HET_nfe_XY=0.000350079;FREQ_HOMALT_nfe_XY=0;AN_nfe_XX=17192;AC_nfe_XX=8;AF_nfe_XX=0.000465;N_BI_GENOS_nfe_XX=8596;N_HOMREF_nfe_XX=8588;N_HET_nfe_XX=8;N_HOMALT_nfe_XX=0;FREQ_HOMREF_nfe_XX=0.999069;FREQ_HET_nfe_XX=0.000930665;FREQ_HOMALT_nfe_XX=0;AN_rmi_XY=392;AC_rmi_XY=1;AF_rmi_XY=0.002551;N_BI_GENOS_rmi_XY=196;N_HOMREF_rmi_XY=195;N_HET_rmi_XY=1;N_HOMALT_rmi_XY=0;FREQ_HOMREF_rmi_XY=0.994898;FREQ_HET_rmi_XY=0.00510204;FREQ_HOMALT_rmi_XY=0;AN_rmi_XX=412;AC_rmi_XX=1;AF_rmi_XX=0.002427;N_BI_GENOS_rmi_XX=206;N_HOMREF_rmi_XX=205;N_HET_rmi_XX=1;N_HOMALT_rmi_XX=0;FREQ_HOMREF_rmi_XX=0.995146;FREQ_HET_rmi_XX=0.00485437;FREQ_HOMALT_rmi_XX=0;AN_sas_XY=1980;AC_sas_XY=2;AF_sas_XY=0.00101;N_BI_GENOS_sas_XY=990;N_HOMREF_sas_XY=988;N_HET_sas_XY=2;N_HOMALT_sas_XY=0;FREQ_HOMREF_sas_XY=0.99798;FREQ_HET_sas_XY=0.0020202;FREQ_HOMALT_sas_XY=0;AN_sas_XX=678;AC_sas_XX=0;AF_sas_XX=0;N_BI_GENOS_sas_XX=339;N_HOMREF_sas_XX=339;N_HET_sas_XX=0;N_HOMALT_sas_XX=0;FREQ_HOMREF_sas_XX=1;FREQ_HET_sas_XX=0;FREQ_HOMALT_sas_XX=0

In [5]:
def parse_info(info_string):

    info_dict = {}

    for item in info_string.split(";"):

        if "=" in item:
            key, value = item.split("=", 1)
            info_dict[key] = value

    return info_dict

In [12]:
rows = []

with gzip.open(
    "../data/raw/gnomad_sv/gnomad.v4.1.sv.sites.vcf.gz",
    "rt"
) as f:

    for line in f:

        if line.startswith("#"):
            continue

        fields = line.strip().split("\t")

        info = parse_info(fields[7])

        rows.append({

            "chromosome": fields[0],

            "start_position": int(fields[1]),

            "end_position": int(info.get("END", fields[1])),

            "sv_type": info.get("SVTYPE"),

            "allele_frequency": float(info.get("AF", 0))

        })

In [7]:
gnomad_sv_df = pd.DataFrame(rows)

gnomad_sv_df.head()

NameError: name 'pd' is not defined

In [8]:
import pandas as pd

In [9]:
gnomad_sv_df = pd.DataFrame(rows)

gnomad_sv_df.head()

  chromosome  start_position  end_position sv_type  allele_frequency
0       chr1           10000        295666     DUP          0.001997
1       chr1           10434         10434     BND          0.114134
2       chr1           10440         10440     BND          0.004201
3       chr1           10450         10450     BND          0.323899
4       chr1           10464         10464     BND          0.036985

In [10]:
gnomad_sv_df = gnomad_sv_df[
    gnomad_sv_df["sv_type"].isin(["DEL", "DUP"])
]

gnomad_sv_df.head()

  chromosome  start_position  end_position sv_type  allele_frequency
0       chr1           10000        295666     DUP          0.001997
7       chr1           11000         51000     DUP          0.067052
9       chr1           22000         30000     DEL          0.014197

In [11]:
gnomad_sv_df["sv_type"].value_counts()

sv_type
DUP    2
DEL    1
Name: count, dtype: int64

In [13]:
gnomad_sv_df.to_csv(
    "../data/interim/gnomad_sv_tables/population_frequency_table.csv",
    index=False
)

In [17]:
gnomad_sv_df = gnomad_sv_df[
    gnomad_sv_df["sv_type"] == "DEL"
]

In [15]:
len(gnomad_sv_df)

1475604

In [18]:
gnomad_sv_df.to_csv(
    "../data/interim/gnomad_sv_tables/population_frequency_table.csv",
    index=False
)